#### Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?

##### 2) How could you create a two-dimensional, 3 x 4 array (three arrays of four elements each) with random numbers from 1 to 10?

##### 3) Create a 4X2 integer array and Prints its attributes.

##### 4) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element. 

##### 5) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element:

#### arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
##### arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

###### 6) Compute the mean, median, minimum, and maximum value of the result array from question 5.

In [2]:
import numpy as np

In [12]:
A = np.arange(10,100)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [15]:
x2 = np.random.randint(1,11, size=(3,4))
x2

array([[ 5,  3,  2,  2],
       [10,  2,  8,  6],
       [10,  9,  3,  6]], dtype=int32)

In [ ]:
A1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(A1)

Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
arr1 = np.array([[0, 3], [5, 5]])
arr2 = np.array([[1, 1], [4, 4]])
arr3 = arr1 + arr2
arr3

array([[1, 4],
       [9, 9]])

In [ ]:
4) #square
arr3 ** 2

array([[ 1, 16],
       [81, 81]])

In [29]:
#5)
X3 = np.array([[5, 6, 9], [21 ,18, 27]])
X4 = np.array([[15 ,33, 24], [4 ,7, 1]])
X5 = X4 + X3
X5

array([[20, 39, 33],
       [25, 25, 28]])

In [33]:
#square of the result
X6 = X5 **2
X6

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [36]:
# printing the mean, median, minimum, maximum
print("Mean:", np.mean(X6))
print("Median:",np.median(X6))
print('Minimum:',np.min(X6))
print('Maximum:',np.max(X6))

Mean: 840.6666666666666
Median: 704.5
Minimum: 400
Maximum: 1521
